name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, everyone"

      - name: Bye
        run: echo "Bye, everyone"
      
